Add intersection types instructions
hexlet-basics/exercises-typescript pull request #102
Opened 2023-01-04 09:48 UTC by mbredikhin

2023-01-04 18:22 UTC, bondiano requested changes

2023-01-04 18:22 UTC, bondiano commented on modules/25-types/30-intersection-types/index.ts
> +function intersection<T extends number | string | boolean | null>(
К этому моменту дженерики еще не пройдены, стоит попроще упражнение придумать

2023-01-24 06:30 UTC, ashikov commented
@mbredikhin и тут :)

2023-02-08 08:22 UTC, ssssank commented
@mbredikhin как у вас дела? нужна ли помощь?

2023-02-28 08:20 UTC, ashikov commented
@mbredikhin здесь тоже. Нужно что-то решать с этими пулреквестами уже)

2023-03-17 06:44 UTC, closed without merging