Add keyof lesson content
hexlet-basics/exercises-typescript pull request #103
Opened 2023-01-04 15:44 UTC by mbredikhin

2023-01-04 18:54 UTC, mokevnin commented
Вау класс, спасибо!

2023-01-05 14:52 UTC, bondiano requested changes
Класс, что принялся писать урок! Всегда буду рад помочь и прокомментировать

2023-01-05 14:52 UTC, bondiano commented on modules/60-working-with-types/10-keyof/description.ru.yml
> +  Для доступа к свойствам объектов, элементам массивов и символах строк в TypeScript мы, как и в JavaScript, используем ключи (индексы).
`keyof` не про получение чего-то по ключу. Попробуй зайти в написание этого урока с реальной проблематики. Например, задай вопрос, что решает `keyof`, что не решить без него. Двигайся в ходе урока к решению заданной проблемы.

2023-01-05 14:52 UTC, bondiano commented on modules/60-working-with-types/10-keyof/description.ru.yml
> +  Оператор keyof так же работает для массивов и строк, тип индексов для них - это number.
Любая справочная информация скорее вторична, если не решает цель урока, и можно отправить читать ссылки. Все же курс не справочник

2023-01-05 14:52 UTC, bondiano commented on modules/60-working-with-types/10-keyof/description.ru.yml
> +  const entries = [['name', 'Vincent'], ['job', 'painter']];
над заданием стоит еще подумать - в `fromEntries` `keyof` не используется и можно куда проще написать

2023-01-24 06:30 UTC, ashikov commented
@mbredikhin как тут дела?

2023-02-08 08:22 UTC, ssssank commented
@mbredikhin как у вас дела? нужна ли помощь?

2023-02-28 08:19 UTC, ashikov commented
@mbredikhin напишите, плиз, будет ли продолжаться работа по этому PR

2023-03-17 06:43 UTC, ssssank commented
Pfrhsdf. GH

2023-03-17 06:43 UTC, closed without merging